# ECollectibleType.py

from enum import Enum

class ECollectibleType(Enum):
    eCT_Invalid = "eCT_Invalid"
    eCT_Begin = "eCT_Begin"
    eCT_Area = "eCT_Area"
    eCT_Butterfly = "eCT_Butterfly"
    eCT_Charm = "eCT_Charm"
    eCT_Damage = "eCT_Damage"
    eCT_Hat = "eCT_Hat"
    eCT_Health = "eCT_Health"
    eCT_LegendaryTreasure = "eCT_LegendaryTreasure"
    eCT_LevelSpecific = "eCT_LevelSpecific"
    eCT_Map = "eCT_Map"
    eCT_Money = "eCT_Money"
    eCT_SoulGem = "eCT_SoulGem"
    eCT_StoryScroll = "eCT_StoryScroll"
    eCT_TreasureChest = "eCT_TreasureChest"
    eCT_Xp = "eCT_Xp"
    eCT_HeroicChallengeDual = "eCT_HeroicChallengeDual"
    eCT_PowerUp = "eCT_PowerUp"
    eCT_Skylander = "eCT_Skylander"
    eCT_MagicItem = "eCT_MagicItem"
    eCT_Pet = "eCT_Pet"
    eCT_RaceModeBonus = "eCT_RaceModeBonus"
    eCT_ScoreModeBonus = "eCT_ScoreModeBonus"
    eCT_Expansion_2011 = "eCT_Expansion_2011"
    eCT_Expansion_2013 = "eCT_Expansion_2013"
    eCT_TurboZone = "eCT_TurboZone"
    eCT_Arena = "eCT_Arena"
    eCT_Max = "eCT_Max"
