# EGroups.py

from enum import Enum

class EGroups(Enum):
    eG_All = "eG_All"
    eG_SinglePlayerStory = "eG_SinglePlayerStory"
    eG_LocalCoopStory = "eG_LocalCoopStory"
    eG_OnlineCoopStory = "eG_OnlineCoopStory"
    eG_SinglePlayerRacing = "eG_SinglePlayerRacing"
    eG_LocalCoopRacing = "eG_LocalCoopRacing"
    eG_OnlineCoopRacing = "eG_OnlineCoopRacing"
    eG_OnlinePublicRacing = "eG_OnlinePublicRacing"
    eG_AllOnline = "eG_AllOnline"
    eG_AllOffline = "eG_AllOffline"
    eG_OnlinePlayAllowed = "eG_OnlinePlayAllowed"
    eG_OnlinePlayRestricted = "eG_OnlinePlayRestricted"
    eG_StoryCompleted = "eG_StoryCompleted"
    eG_PhysicalPortal = "eG_PhysicalPortal"
    eG_NoPortal = "eG_NoPortal"
    eG_CollectionSizeLowerQuintile = "eG_CollectionSizeLowerQuintile"
    eG_CollectionSizeLowerMiddleQuintile = "eG_CollectionSizeLowerMiddleQuintile"
    eG_CollectionSizeMiddleQuintile = "eG_CollectionSizeMiddleQuintile"
    eG_CollectionSizeUpperMiddleQuintile = "eG_CollectionSizeUpperMiddleQuintile"
    eG_CollectionSizeUpperQuintile = "eG_CollectionSizeUpperQuintile"
    eG_ReturningPlayer = "eG_ReturningPlayer"
    eG_NewPlayer = "eG_NewPlayer"
    eG_ToysOwnedOutsideStarterPack = "eG_ToysOwnedOutsideStarterPack"
    eG_DarkEditionStarterPack = "eG_DarkEditionStarterPack"
    eG_StarterPack = "eG_StarterPack"
    eG_BothStarterPacks = "eG_BothStarterPacks"
    eG_InstantsOnly = "eG_InstantsOnly"
    eG_NoStarterPackOrInstantToys = "eG_NoStarterPackOrInstantToys"
    eG_LandRace = "eG_LandRace"
    eG_SeaRace = "eG_SeaRace"
    eG_AirRace = "eG_AirRace"
    eG_NumGroups = "eG_NumGroups"
