# ENetworkEventCategory.py

from enum import Enum

class ENetworkEventCategory(Enum):
    eNEC_Invalid = "eNEC_Invalid"
    eNEC_Reserved = "eNEC_Reserved"
    eNEC_GameStart = "eNEC_GameStart"
    eNEC_LevelEnd = "eNEC_LevelEnd"
    eNEC_LevelStart = "eNEC_LevelStart"
    eNEC_MatchEnd = "eNEC_MatchEnd"
    eNEC_StorePurchase = "eNEC_StorePurchase"
    eNEC_TabletPurchase = "eNEC_TabletPurchase"
    eNEC_StoreEntry = "eNEC_StoreEntry"
    eNEC_MessageClick = "eNEC_MessageClick"
    eNEC_MessageView = "eNEC_MessageView"
    eNEC_ToyChange = "eNEC_ToyChange"
    eNEC_Skystones = "eNEC_Skystones"
    eNEC_LockPuzzle = "eNEC_LockPuzzle"
    eNEC_MiniGame = "eNEC_MiniGame"
    eNEC_SoulGem = "eNEC_SoulGem"
    eNEC_ToyDeath = "eNEC_ToyDeath"
    eNEC_ToyLevelUp = "eNEC_ToyLevelUp"
    eNEC_NPCInteraction = "eNEC_NPCInteraction"
    eNEC_ModeSelected = "eNEC_ModeSelected"
    eNEC_MenuClosed = "eNEC_MenuClosed"
    eNEC_DriverChallenge = "eNEC_DriverChallenge"
    eNEC_ElementalZone = "eNEC_ElementalZone"
    eNEC_ComscoreStart = "eNEC_ComscoreStart"
    eNEC_ComscoreEnd = "eNEC_ComscoreEnd"
