# ENicknameKeyboardAnims.py

from enum import Enum

class ENicknameKeyboardAnims(Enum):
    eNKA_In = "eNKA_In"
    eNKA_Out = "eNKA_Out"
    eNKA_KeySelected = "eNKA_KeySelected"
    eNKA_KeyUnselected = "eNKA_KeyUnselected"
    eNKA_KeyPressed = "eNKA_KeyPressed"
    eNKA_KeyUnselectedPressed = "eNKA_KeyUnselectedPressed"
    eNKA_KeyEmpty = "eNKA_KeyEmpty"
    eNKA_BackspaceSelected = "eNKA_BackspaceSelected"
    eNKA_BackspaceSelected2 = "eNKA_BackspaceSelected2"
    eNKA_BackspaceUnselected = "eNKA_BackspaceUnselected"
    eNKA_BackspaceUnselected2 = "eNKA_BackspaceUnselected2"
    eNKA_BackspacePressed = "eNKA_BackspacePressed"
    eNKA_BackspaceUnselectedPressed = "eNKA_BackspaceUnselectedPressed"
    eNKA_ChangeLayoutSelected = "eNKA_ChangeLayoutSelected"
    eNKA_ChangeLayoutSelected2 = "eNKA_ChangeLayoutSelected2"
    eNKA_ChangeLayoutUnselected = "eNKA_ChangeLayoutUnselected"
    eNKA_ChangeLayoutUnselected2 = "eNKA_ChangeLayoutUnselected2"
    eNKA_ChangeLayoutPressed = "eNKA_ChangeLayoutPressed"
    eNKA_ChangeLayoutUnselectedPressed = "eNKA_ChangeLayoutUnselectedPressed"
    eNKA_ShiftSelected = "eNKA_ShiftSelected"
    eNKA_ShiftUnselected = "eNKA_ShiftUnselected"
    eNKA_ShiftPressed = "eNKA_ShiftPressed"
    eNKA_ShiftUnselectedPressed = "eNKA_ShiftUnselectedPressed"
    eNKA_ToUpper = "eNKA_ToUpper"
    eNKA_ToLower = "eNKA_ToLower"
    eNKA_KeyFilled = "eNKA_KeyFilled"
    eNKA_DoneSelected = "eNKA_DoneSelected"
    eNKA_DoneUnselected = "eNKA_DoneUnselected"
    eNKA_DonePressed = "eNKA_DonePressed"
    eNKA_SpaceSelected = "eNKA_SpaceSelected"
    eNKA_SpaceUnselected = "eNKA_SpaceUnselected"
    eNKA_SpacePressed = "eNKA_SpacePressed"
    eNKA_SpaceUnselectedPressed = "eNKA_SpaceUnselectedPressed"
    eNKA_CaretIdle = "eNKA_CaretIdle"
    eNKA_Count = "eNKA_Count"
