# EOptions.py

from enum import Enum

class EOptions(Enum):
    eO_GLOBAL = "eO_GLOBAL"
    eO_GLOBAL = "eO_GLOBAL"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_BRANCH = "eO_BRANCH"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_LEAF = "eO_LEAF"
    eO_FROND = "eO_FROND"
    eO_FROND = "eO_FROND"
    eO_FROND = "eO_FROND"
    eO_NUM = "eO_NUM"
