# EPlayerStateKey.py

from enum import Enum

class EPlayerStateKey(Enum):
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_Map = "ePSK_Map"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_GamePlay = "ePSK_GamePlay"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToyPrimary = "ePSK_ToyPrimary"
    ePSK_ToySecondary = "ePSK_ToySecondary"
    ePSK_ToySecondary = "ePSK_ToySecondary"
    ePSK_ToySecondary = "ePSK_ToySecondary"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Multiplayer = "ePSK_Multiplayer"
    ePSK_Max = "ePSK_Max"
