# ESaveGameVersion.py

from enum import Enum

class ESaveGameVersion(Enum):
    eSGV_INVALID = "eSGV_INVALID"
    eSGV_InitialVersion = "eSGV_InitialVersion"
    eSGV_StatManagerUpdatedForSaveMerging2 = "eSGV_StatManagerUpdatedForSaveMerging2"
    eSGV_AddingSoundSystemSaveInfo = "eSGV_AddingSoundSystemSaveInfo"
    eSGV_AddedFieldsToCStatsData = "eSGV_AddedFieldsToCStatsData"
    eSGV_AddingLegendaryProgression = "eSGV_AddingLegendaryProgression"
    eSGV_RemovingRecentBoostData = "eSGV_RemovingRecentBoostData"
    eSGV_ReducedSaveBufferSize = "eSGV_ReducedSaveBufferSize"
    eSGV_DlcRemovedOrAdded = "eSGV_DlcRemovedOrAdded"
    eSGV_TrackingMoreCollectibles = "eSGV_TrackingMoreCollectibles"
    eSGV_UsingItemNameInsteadofItemIndex = "eSGV_UsingItemNameInsteadofItemIndex"
    eSGV_InventoryNoLongerSavesItems = "eSGV_InventoryNoLongerSavesItems"
    eSGV_RemoveAutoSpend = "eSGV_RemoveAutoSpend"
    eSGV_AddSaveLoadCallbacks = "eSGV_AddSaveLoadCallbacks"
    eSGV_AddToyCollection = "eSGV_AddToyCollection"
    eSGV_ChangedCollectibleSaving = "eSGV_ChangedCollectibleSaving"
    eSGV_IGXifiedSaveFile = "eSGV_IGXifiedSaveFile"
    eSGV_SaveFileThumbnailSupport = "eSGV_SaveFileThumbnailSupport"
    eSGV_MovedSkylanderCollectionToGlobal = "eSGV_MovedSkylanderCollectionToGlobal"
    eSGV_RemovedLegsToyCollectibleTrackers = "eSGV_RemovedLegsToyCollectibleTrackers"
    eSGV_SaveChapterObjectives = "eSGV_SaveChapterObjectives"
    eSGV_CollectionMatrixRowVsColumnMajorChanged = "eSGV_CollectionMatrixRowVsColumnMajorChanged"
    eSGV_StoryStarsSavedAsBitMask = "eSGV_StoryStarsSavedAsBitMask"
    eSGV_AllToyCollectiblesToGlobalSave = "eSGV_AllToyCollectiblesToGlobalSave"
    eSGV_ConvertedStatsToIntegerFromFloat = "eSGV_ConvertedStatsToIntegerFromFloat"
    eSGV_AddedUserSlotBasedSessionInfo = "eSGV_AddedUserSlotBasedSessionInfo"
    eSGV_SavePortalMasterRankAndStardust = "eSGV_SavePortalMasterRankAndStardust"
    eSGV_SaveSkystonesSmashDeck = "eSGV_SaveSkystonesSmashDeck"
    eSGV_CollectibleShopSupportAdded = "eSGV_CollectibleShopSupportAdded"
    eSGV_LevelCompletionCountInZoneInfo = "eSGV_LevelCompletionCountInZoneInfo"
    eSGV_EmblemsMinusRacingSupport = "eSGV_EmblemsMinusRacingSupport"
    eSGV_AllCollectiblesToGlobalSave = "eSGV_AllCollectiblesToGlobalSave"
    eSGV_GameStateToGlobalSave = "eSGV_GameStateToGlobalSave"
    eSGV_GameVariableLifetime = "eSGV_GameVariableLifetime"
    eSGV_SkystonesTutorial = "eSGV_SkystonesTutorial"
    eSGV_AccoladesMovedToGlobal = "eSGV_AccoladesMovedToGlobal"
    eSGV_MissingGameStates = "eSGV_MissingGameStates"
    eSGV_SkystonesDifficulty = "eSGV_SkystonesDifficulty"
    eSGV_RemovedWoodburrowVariables = "eSGV_RemovedWoodburrowVariables"
    eSGV_AddedFarthestCheckpoint = "eSGV_AddedFarthestCheckpoint"
    eSGV_RemovedInvertedFlightControls = "eSGV_RemovedInvertedFlightControls"
    eSGV_AddedSaveSlotDataForChapter = "eSGV_AddedSaveSlotDataForChapter"
    eSGV_AddedStoryCompletedToGameState = "eSGV_AddedStoryCompletedToGameState"
    eSGV_ObjectSizesChanged = "eSGV_ObjectSizesChanged"
    eSGV_NEXT = "eSGV_NEXT"
